### ISSUE TITLE
Variables hard_drive, host_name, etc shouldn't need to be globals

### ISSUE THREAD

**Issue by TheMowgliMan** [Orange-OS-LE/OrangeOSLE2#4]
These variables should already be accessible due to the way they were initialized.

**Comment by michaeleldar** [comment]
? I don't understand what you mean? In python, you can only edit global variables in functions if you do "global x"

**Comment by TheMowgliMan** [comment]
I don't know where you got this from, but in Python 3 global file variables
(defined in the highest scope, i.e. in the file at the top outside of any
indented blocks) can be accessed and edited in all functions normally. This
is sometimes needed when a script loads a Python script into a variable and
then executes it via code, but not otherwise.

**Comment by michaeleldar** [comment]
See this:

https://github.com/Orange-OS-LE/OrangeOSLE2/assets/66514999/2c9b3536-9112-48fc-8e34-dabb3f90fc68

**Comment by TheMowgliMan** [comment]
Odd. Let me look into this, usually that's not how scope works in my
experience.
